### ISSUE TITLE
Returning to title or exiting game loses any reminders that had triggered in the partial day played.

### ISSUE THREAD

**Issue by Json-x-ly** [Dem1se/SDVMods#10]
I had an unrelated issue in SDV that caused be to have to restart the game a few times and noticed that any reminders that are triggered in a partially played day did not trigger again when the save is reloaded and that day repeated. I poked through the source to feed my curiosity and noticed that you do a straight `File.Delete(filePathAbsolute)` immediately after a reminder has been triggered. If you instead stored the file paths in a collection and deleted them when a new Saved event was called, the behavior would be more consistent with the rest of the games serialization systems.

I went ahead and implemented the feature in a local commit for my own use, I found several other areas that needed accommodations to compensate for this change and have been using it for a day or so. Let me know if you'd be interested in looking at any of it.

Big fan of the mod btw.

**Comment by Dem1se** [comment]
Yeah, I've thought about this too, but I realized it wasn't at the top priority at that point as I had a bunch of other areas to work on.
But yeah, your implementation sounds nice, I'd love to see what you've done, so create a PR if you'd like! 
Thanks.

**Comment by Json-x-ly** [comment]
Alright, I'll set that up later today after I get off work.
