### ISSUE TITLE
[Time Settings] Cant set midnight - 2am reminders

### ISSUE THREAD

**Issue by DrKittens** [Dem1se/SDVMods#18]
Steps to Reproduce:
- Press F2 set reminder text "GO TO BED"
- Select The Current Season
- Select the Day after the current day
- Check box for recurring (optional) and pick 1 day for daily reminders
- Click 1 then :30 then AM to create a 1:30am reminder
- Click Apply

What happens:
- Addon tells me 1:30am is not a valid reminder time when it is part of the vanilla SDV day-cycle and fails to set a reminder

Expected Behaviour:
- I successfully set a (recurring daily) 1:30am reminder starting the following day (technically tonight) with text "GO TO BED"

Requested Solution:

1200am / 12:30am / 1am / 1:30am should all be valid reminder times.

Potentially related / same as #12 but i read that as a AM / PM mixup not an invalid time related error.

**Comment by Dem1se** [comment]
This is related to an arbitrary design decision I think, I'll look into it.
