### ISSUE TITLE
Custom Reminders behaves odd with zoom levels

### ISSUE THREAD

**Issue by SodiumShine** [Dem1se/SDVMods#9]
I've found that having the zoom level set to certain levels (particularly high or low extremes) causes the UI to function strangely. 

When zoomed in too far, the whole UI is partly off screen, and when zoomed out too far, the date cannot be viewed on entries by mouse-over. Not to mention at any level the whole UI shifts with zoom.

![image](https://user-images.githubusercontent.com/4461697/103831823-0956c300-50d1-11eb-8491-290f9bbf8eea.png)

![image](https://user-images.githubusercontent.com/4461697/103831860-1d022980-50d1-11eb-8fa1-3549243e7a41.png)

**Comment by SodiumShine** [comment]
Oh and as a side note, other mods that allow you to zoom past the game's normal restrictions causes the interface to be even more offset to the point it becomes unusable. This doesn't happen with other interfaces so I'm not sure what's going on there.

**Comment by Dem1se** [comment]
Hello, thanks for bringing this to my attention.
Can you try out this build and tell me if it fixes the issue.

https://drive.google.com/file/d/1ztbzi637n-9MXB4G5SLOJnAXQRAOlcwm/view?usp=sharing

**Comment by SodiumShine** [comment]
The UI itself no longer slides off the screen, but the space to mouse over reminders is still offset by zoom level. Previously I just thought it wasn't working but it turns out it was like this.

![image](https://user-images.githubusercontent.com/4461697/104076398-11963600-526a-11eb-8f11-ab5bf3fb46c4.png)

![image](https://user-images.githubusercontent.com/4461697/104076411-1eb32500-526a-11eb-9910-a26cc577086b.png)

**Comment by SodiumShine** [comment]
Ah bad news. Scaling the UI itself causes offset issues too...

**Comment by Dem1se** [comment]
Yeah, I added uiScale compensation as well now.
I can't recreate the hoverzone issue however.

Can you head over to the Nexus page and try the new beta-2 that's on there and tell me if it fixes most of the issues.

The thing is SDV actually doesn't support global scaling for a menu and most of the UI elements don't support scaling as well like the text, etc. So there's not much I can do about things that overflow out of the screen in the extreme settings.

I've tried something and made the scroll reposition to the side after a point. I also tried messing with the scale of the some elements, but it looks horrible. So unless something's not working right, this is the most that can be done really, and I think it's really usable right now.

**Comment by SodiumShine** [comment]
Looks good! Scales with UI and zoom levels decently.

I'm not sure why I'm having the hoverzone issue then. I'm not doing anything besides changing the zoom level, so I'm going to have to assume another mod is conflicting at this point. 

Thanks for your hard work.

**Comment by Dem1se** [comment]
Thanks for creating this issue!

Let me know if you find the mod conflict.
